language: ruby
rvm:
  - 2.1.2
  - 1.9.3
  - jruby-19mode
  - ruby-head
  - jruby-head
script: rake test
notifications:
  webhooks: https://gd-radiator.ngrok.com/hubot/travis?room=devlab@conference.im.office.gdi
  on_success: always
  on_failure: always